[package]
name = "tasc"
version = "0.1.0"
edition = "2021"

[features]
default = ["std", "global"]
global = ["std"]
std = ["dep:crossbeam-channel"]

[dependencies]
spin = "0.9.8"
crossbeam-channel = { version = "0.5.13", optional = true }
